import type { TournamentDataset } from "./types";

export const sampleDataset: TournamentDataset = {
  tournament: {
    id: "t-2026",
    code: "seoul-open-2026",
    name: "서울 쇼다운 오픈 2026",
    location: "서울특별시 체육문화센터",
    startDate: "2026-07-11",
    endDate: "2026-07-12",
    timezone: "Asia/Seoul",
    status: "running",
  },
  divisions: [
    {
      id: "d-men",
      tournamentId: "t-2026",
      name: "남자부",
      code: "M",
      category: "male",
      sortOrder: 1,
      isActive: true,
    },
    {
      id: "d-women",
      tournamentId: "t-2026",
      name: "여자부",
      code: "W",
      category: "female",
      sortOrder: 2,
      isActive: true,
    },
  ],
  players: [
    { id: "p-1", displayName: "김철수", countryCode: "KOR" },
    { id: "p-2", displayName: "박영희", countryCode: "KOR" },
    { id: "p-3", displayName: "이민준", countryCode: "KOR" },
    { id: "p-4", displayName: "최서연", countryCode: "KOR" },
    { id: "p-5", displayName: "Alex Novak", countryCode: "SVK" },
    { id: "p-6", displayName: "Mina Tanaka", countryCode: "JPN" },
    { id: "p-7", displayName: "Anna Smith", countryCode: "GBR" },
    { id: "p-8", displayName: "조하은", countryCode: "KOR" },
  ],
  tournamentPlayers: [
    {
      id: "tp-1",
      tournamentId: "t-2026",
      divisionId: "d-men",
      playerId: "p-1",
      seedNo: 1,
      entryNo: 1,
      clubName: "서울클럽",
      status: "active",
    },
    {
      id: "tp-2",
      tournamentId: "t-2026",
      divisionId: "d-men",
      playerId: "p-3",
      seedNo: 2,
      entryNo: 2,
      clubName: "인천클럽",
      status: "active",
    },
    {
      id: "tp-3",
      tournamentId: "t-2026",
      divisionId: "d-men",
      playerId: "p-5",
      seedNo: 3,
      entryNo: 3,
      clubName: "Bratislava SC",
      status: "active",
    },
    {
      id: "tp-4",
      tournamentId: "t-2026",
      divisionId: "d-men",
      playerId: "p-1",
      seedNo: 4,
      entryNo: 4,
      displayNameOverride: "김철수 B",
      clubName: "서울클럽",
      status: "active",
    },
    {
      id: "tp-5",
      tournamentId: "t-2026",
      divisionId: "d-women",
      playerId: "p-2",
      seedNo: 1,
      entryNo: 1,
      clubName: "수원클럽",
      status: "active",
    },
    {
      id: "tp-6",
      tournamentId: "t-2026",
      divisionId: "d-women",
      playerId: "p-4",
      seedNo: 2,
      entryNo: 2,
      clubName: "대전클럽",
      status: "active",
    },
    {
      id: "tp-7",
      tournamentId: "t-2026",
      divisionId: "d-women",
      playerId: "p-6",
      seedNo: 3,
      entryNo: 3,
      clubName: "Tokyo Stars",
      status: "active",
    },
    {
      id: "tp-8",
      tournamentId: "t-2026",
      divisionId: "d-women",
      playerId: "p-8",
      seedNo: 4,
      entryNo: 4,
      clubName: "광주클럽",
      status: "active",
    },
  ],
  officials: [
    {
      id: "o-1",
      tournamentId: "t-2026",
      name: "정심판",
      shortCode: "J1",
      roleName: "REFEREE",
      active: true,
    },
  ],
  stages: [
    {
      id: "s-men-league",
      tournamentId: "t-2026",
      divisionId: "d-men",
      name: "조별 리그",
      stageType: "round_robin",
      sortOrder: 1,
    },
    {
      id: "s-women-league",
      tournamentId: "t-2026",
      divisionId: "d-women",
      name: "조별 리그",
      stageType: "round_robin",
      sortOrder: 1,
    },
  ],
  groups: [
    {
      id: "g-men-a",
      tournamentId: "t-2026",
      divisionId: "d-men",
      stageId: "s-men-league",
      code: "M_A",
      name: "남자부 GROUP A",
      groupType: "league",
      sortOrder: 1,
    },
    {
      id: "g-women-a",
      tournamentId: "t-2026",
      divisionId: "d-women",
      stageId: "s-women-league",
      code: "W_A",
      name: "여자부 GROUP A",
      groupType: "league",
      sortOrder: 1,
    },
  ],
  matches: [
    {
      id: "m-1",
      tournamentId: "t-2026",
      divisionId: "d-men",
      stageId: "s-men-league",
      groupId: "g-men-a",
      matchNo: 1,
      scheduledAt: "2026-07-11T09:30:00+09:00",
      durationMinutes: 30,
      courtName: "Table 1",
      refereeName: "정심판",
      status: "completed",
      endReason: "normal",
      player1TournamentPlayerId: "tp-1",
      player2TournamentPlayerId: "tp-2",
      winnerTournamentPlayerId: "tp-1",
      player1MatchPoints: 1,
      player2MatchPoints: 0,
      player1SetsWon: 2,
      player2SetsWon: 0,
      player1TotalPoints: 22,
      player2TotalPoints: 13,
      version: 2,
      sets: [
        {
          id: "set-1",
          matchId: "m-1",
          setNo: 1,
          player1Score: 11,
          player2Score: 5,
          winnerSide: "player1",
        },
        {
          id: "set-2",
          matchId: "m-1",
          setNo: 2,
          player1Score: 11,
          player2Score: 8,
          winnerSide: "player1",
        },
      ],
    },
    {
      id: "m-2",
      tournamentId: "t-2026",
      divisionId: "d-men",
      stageId: "s-men-league",
      groupId: "g-men-a",
      matchNo: 2,
      scheduledAt: "2026-07-11T10:00:00+09:00",
      durationMinutes: 30,
      courtName: "Table 2",
      refereeName: "오심판",
      status: "scheduled",
      endReason: "normal",
      player1TournamentPlayerId: "tp-3",
      player2TournamentPlayerId: "tp-4",
      player1MatchPoints: 0,
      player2MatchPoints: 0,
      player1SetsWon: 0,
      player2SetsWon: 0,
      player1TotalPoints: 0,
      player2TotalPoints: 0,
      version: 1,
      sets: [],
    },
    {
      id: "m-3",
      tournamentId: "t-2026",
      divisionId: "d-women",
      stageId: "s-women-league",
      groupId: "g-women-a",
      matchNo: 3,
      scheduledAt: "2026-07-11T10:30:00+09:00",
      durationMinutes: 30,
      courtName: "Table 1",
      refereeName: "한심판",
      status: "running",
      endReason: "normal",
      player1TournamentPlayerId: "tp-5",
      player2TournamentPlayerId: "tp-6",
      player1MatchPoints: 0,
      player2MatchPoints: 0,
      player1SetsWon: 1,
      player2SetsWon: 0,
      player1TotalPoints: 11,
      player2TotalPoints: 7,
      version: 3,
      sets: [
        {
          id: "set-3",
          matchId: "m-3",
          setNo: 1,
          player1Score: 11,
          player2Score: 7,
          winnerSide: "player1",
        },
      ],
    },
    {
      id: "m-4",
      tournamentId: "t-2026",
      divisionId: "d-women",
      stageId: "s-women-league",
      groupId: "g-women-a",
      matchNo: 4,
      scheduledAt: "2026-07-11T11:00:00+09:00",
      durationMinutes: 30,
      courtName: "Table 2",
      refereeName: "송심판",
      status: "scheduled",
      endReason: "normal",
      player1TournamentPlayerId: "tp-7",
      player2TournamentPlayerId: "tp-8",
      player1MatchPoints: 0,
      player2MatchPoints: 0,
      player1SetsWon: 0,
      player2SetsWon: 0,
      player1TotalPoints: 0,
      player2TotalPoints: 0,
      version: 1,
      sets: [],
    },
  ],
  rankings: [
    {
      id: "r-1",
      tournamentId: "t-2026",
      divisionId: "d-men",
      stageId: "s-men-league",
      groupId: "g-men-a",
      tournamentPlayerId: "tp-1",
      rankNo: 1,
      matchesPlayed: 1,
      wins: 1,
      losses: 0,
      matchPoints: 1,
      setsWon: 2,
      setsLost: 0,
      setDifference: 2,
      pointsFor: 22,
      pointsAgainst: 13,
      pointDifference: 9,
    },
    {
      id: "r-2",
      tournamentId: "t-2026",
      divisionId: "d-men",
      stageId: "s-men-league",
      groupId: "g-men-a",
      tournamentPlayerId: "tp-2",
      rankNo: 2,
      matchesPlayed: 1,
      wins: 0,
      losses: 1,
      matchPoints: 0,
      setsWon: 0,
      setsLost: 2,
      setDifference: -2,
      pointsFor: 13,
      pointsAgainst: 22,
      pointDifference: -9,
    },
    {
      id: "r-3",
      tournamentId: "t-2026",
      divisionId: "d-men",
      stageId: "s-men-league",
      groupId: "g-men-a",
      tournamentPlayerId: "tp-3",
      rankNo: 3,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      matchPoints: 0,
      setsWon: 0,
      setsLost: 0,
      setDifference: 0,
      pointsFor: 0,
      pointsAgainst: 0,
      pointDifference: 0,
    },
    {
      id: "r-4",
      tournamentId: "t-2026",
      divisionId: "d-women",
      stageId: "s-women-league",
      groupId: "g-women-a",
      tournamentPlayerId: "tp-5",
      rankNo: 1,
      matchesPlayed: 1,
      wins: 0,
      losses: 0,
      matchPoints: 0,
      setsWon: 1,
      setsLost: 0,
      setDifference: 1,
      pointsFor: 11,
      pointsAgainst: 7,
      pointDifference: 4,
      tieBreakNote: "진행 중 경기의 현재 세트만 반영된 임시 순위입니다.",
    },
  ],
};
